server:
  port: 8090


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: ngbs
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.98.154.117:3306/test?autoReconnect=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=true
    username: work
    password: Yeweiqqiang007!


mybatis:
  mapper-locations: classpath*:mappers/*.xml